version: "3"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6380:6380"
    volumes:
      - ./database-volume:/var/lib/redis/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - ./database-volume:/var/lib/mongodb/data
